// themes.ts

export const THEMES = {
  babyblue: {
    textColor: '#ebf3f3',
    welcomeColor: '#6fd6ff',
    zodiacImage: '#ebf3f3',
    avatarContainerColor: '#6fd6ff',
    moodContainerColor: '#8888df',
    cardImage: require('../../assets/cards/babyblue.png'),
    topContainer: '#ecf2f5',
    bottomContainer: '#c0d4db',

  },
  garden: {
    textColor: '#fffae7',
    welcomeColor: '#bd8d56',
    zodiacImage: '#fffae7',
    avatarContainerColor: '#e7e9c2',
    moodContainerColor: '#fee6c4',
    cardImage: require('../../assets/cards/garden.png'),
    topContainer: '#fffae7',
    bottomContainer: '#fffae7',
  },
  grape: {
    textColor: '#332b32',
    welcomeColor: '#3c2539',
    zodiacImage: '#332b32',
    avatarContainerColor: '#aea5ae',
    moodContainerColor: '#edcbcb',
    cardImage: require('../../assets/cards/grape.png'),
    topContainer: '#686d83',
    bottomContainer: '#322a31',
  },
  redish: {
    textColor: '#fdc7a5',
    welcomeColor: '#ebf3f3',
    zodiacImage: '#c5653a',
    avatarContainerColor: '#ffbb89',
    moodContainerColor: '#c5653a',
    cardImage: require('../../assets/cards/redish.png'),
    topContainer: '#fdc7a5',
    bottomContainer: '#fdc7a5',
  },
  yogurt: {
    textColor: '#f9e5e7',
    welcomeColor: '#c27a7e',
    zodiacImage: '#c27a7e',
    avatarContainerColor: '#e9c6ca',
    moodContainerColor: '#c27a7e',
    cardImage: require('../../assets/cards/yogurt.png'),
    topContainer: '#f9e5e7',
    bottomContainer: '#f9e5e7',
  },
  clouds: {
    textColor: '#f9e5e7',
    welcomeColor: '#c27aad',
    zodiacImage: '#f9e5e7',
    avatarContainerColor: '#8087be',
    moodContainerColor: '#33305b',
    cardImage: require('../../assets/cards/clouds.png'),
    topContainer: '#33305b',
    bottomContainer: '#33305b',
  },
  dunes: {
    textColor: '#f9e5e7',
    welcomeColor: '#c85342',
    zodiacImage: '#ac4e46',
    avatarContainerColor: '#fc7b51',
    moodContainerColor: '#ac4e46',
    cardImage: require('../../assets/cards/dunes.png'),
    topContainer: '#33305b',
    bottomContainer: '#0e1b2e',
  },

};
